build-and-test - make test fail if it has FAILs in it
Now it seems to pass though it actually fails.
(Although locally I can see that go test returns 1 in case of fail).

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -38,6 +38,12 @@ jobs:
         run: |
           echo "## Go test" >> $GITHUB_STEP_SUMMARY
           go test -v -cover ./... |tee gotest.log >> $GITHUB_STEP_SUMMARY
+          if grep -q "FAIL" gotest.log; then
+            echo "## Go test failed" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          else
+            echo "## Go test passed" >> $GITHUB_STEP_SUMMARY
+          fi
       - name: Post status to Slack testing_builds
         if: always()
         uses: act10ns/slack@v2
